### ISSUE TITLE
Does this work the same after upgrading to Google Analytics?

### ISSUE THREAD

**Issue by oneseedfruit** [DrMoriarty/godot-firebase-analytics#1]
Hi, thanks for making this. 

I'd like to ask if this works the same after upgrading to Google Analytics (as shown in the screenshot)?

![Screenshot_2021-02-18 Firebase Analytics + Remote Config on the Web - YouTube](https://user-images.githubusercontent.com/5054104/108349957-9176cf00-721e-11eb-9162-fe6c12076297.png)

**Comment by DrMoriarty** [comment]
Yes, the plugin just will send data to google analytics when you upgrade.
