### ISSUE TITLE
Google Analytics for Firebase version does not match Google App Measurement

### ISSUE THREAD

**Issue by kyoz** [DrMoriarty/godot-firebase-analytics#10]
When try running with firebase-analytics plugin on iOS, i'v face this problem and is cause the app the crash immediately on load. Is there any fix for this like changing Google App Measurement version @@

```
*** Terminating app due to uncaught exception 'FIRAnalyticsVersionMismatch', reason: 'Google Analytics for Firebase version (70100000) does not match with Google App Measurement (80101000) version. Please update.'
terminating with uncaught exception of type NSException
```

**Comment by DrMoriarty** [comment]
Do you use any firebase frameworks in addition to firebase-analytics plugin?

**Comment by kyoz** [comment]
This is the list of current plugins i'm using:

[Admob](https://github.com/Poing-Studios/godot-admob-ios) - 1.1.0
[Local Notification](https://github.com/DrMoriarty/godot-local-notification) - 0.2.2
[Firebase Analytics](https://github.com/DrMoriarty/godot-firebase-analytics) - 0.2.2

**Comment by kyoz** [comment]
I don't know exactly if Admob plugins is using firebase or not. I'v search through the code and it seem doesn't use Firebase @@

**Comment by kyoz** [comment]
<img width="578" alt="Screen Shot 2021-08-22 at 16 34 47" src="https://user-images.githubusercontent.com/29815830/130350229-21146b0c-3164-42b2-bd3c-b64f107dea19.png">

Just found out, seem that's by the admob plugins. To solve this problem, do i have to rebuild that plugin or just copy and paste the GoogleAppMeasurement in Firebase Analytics plugin to Admob plugin :D..

Thank you very much

**Comment by kyoz** [comment]
<img width="312" alt="Screen Shot 2021-08-22 at 16 49 45" src="https://user-images.githubusercontent.com/29815830/130350562-62356afb-643c-467e-87a1-9e11d55e8406.png">

This is my currently Framework folders in Xcode project

**Comment by kyoz** [comment]
For more information, the Admob Plugin is using [Google Mobile Ads SDK (8.9.0)](https://developers.google.com/admob/ios/download)

**Comment by DrMoriarty** [comment]
Yes, this is a version mismatch issue. Try to change GoogleAppMeasurement in AdMob with version from firebase plugin (or vice verce if this don't work)
At any time you can reinstall NativeLib plugins in order to rollback all changes in them.

**Comment by kyoz** [comment]
Thank you so much, i'll give it a try :D
