### ISSUE TITLE
Firebase analytics not running

### ISSUE THREAD

**Issue by sandoche** [DrMoriarty/godot-firebase-analytics#12]
Hi,

I did the setup following the documentation.
When I run the code there is no crash and no error.

When I run:
```
adb logcat -e FirebaseAnalytics
```

I don't see anything.

So it looks like it's not running.

I do have this file `android/build/google-services.json`

In autoload I do have this
![image](https://user-images.githubusercontent.com/3635348/137510349-edc7278f-86e7-4306-99a6-883ca86c03be.png)

And this is what I have in my first screen
![image](https://user-images.githubusercontent.com/3635348/137510463-60837060-b54d-4c7a-bcff-c2e4e3c69404.png)

Do you know what could I've done wrong?

Also I don't see anything in the gradle no reference to firebase at all.
I used the GUI to install the package.

**Comment by sandoche** [comment]
Also I noticed that when I installed the package the console got stuck there not sure it finished the installation:
```
Checking project dependencies: firebase-core@0.1.1, nativelib-export@0.2.0
Found installed firebase-core@0.1.1
Found installed nativelib-export@0.2.0
Installing firebase-analytics@0.2.2
  Unpack firebase-analytics_0.2.2_all.tgz
```

**Comment by sandoche** [comment]
The `\android\plugins` was empty.

**Comment by DrMoriarty** [comment]
You should enable Android platform on NativeLib view (in the top) and then reinstall all plugins again.

**Comment by sandoche** [comment]
@DrMoriarty thanks it did add all the plugins this time but I still don't see anything neither on firebase realtime nor when using this. Basically updated `.nativelib` and added files in `plugin`.
```
adb logcat -e FirebaseAnalytics
```
I did activate the Verbose Stdout before running it in my device.

**Comment by sandoche** [comment]
The "NativeLib export plugin" was disabled, will try again after activating.

**Comment by sandoche** [comment]
It didn't help unfortunately :(

**Comment by sandoche** [comment]
The plugin was not activated in the export settings.
Maybe it would be nice to add it to the documentation. I discovered that reading other solved issues.

**Comment by sandoche** [comment]
Doing some progress but still not right, here are the results of `adb logcat -e FirebaseAnalytics`
```
10-15 18:31:09.023  1543  1543 I GodotPluginRegistry: Initializing Godot plugin FirebaseAnalytics
10-15 18:31:09.024  1543  1543 I GodotPluginRegistry: Completed initialization for Godot plugin FirebaseAnalytics
10-15 18:31:09.404  1543  1603 I godot   : FirebaseAnalytics plugin inited!
```

I don't see any log about the screen event I am sending.
And nothing in firebase console.

**Comment by sandoche** [comment]
Actually I also did this `adb logcat -e google_app_id` to see if I had the same as https://github.com/DrMoriarty/godot-firebase-analytics/issues/7
And I do. I get
```
10-15 18:31:22.005  1543  1580 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
```
Will keep you updated.

**Comment by sandoche** [comment]
It worked after following this:
https://goo.gl/NAOOOI

I will try to document this.

**Comment by sandoche** [comment]
Here is my guide: https://gist.github.com/sandoche/0109849ef96c87bba8f436c58d342039
