### ISSUE TITLE
malloc ERROR + 1504 Warnings

### ISSUE THREAD

**Issue by SnailRabbids** [DrMoriarty/godot-firebase-analytics#17]
@DrMoriarty  Hi, I have 1504 issues if firebase-analytics IOS plugin is enabled (same for "RateMe" plugin). Do you have some ideas, why it happens? I have 0 warnings w/o them. Mb I have to update something? Will be very grateful for any help :)

Godot v3.4.4.stable
Plugin was installed from NativeLib and works as expected. The problem is in 1500 warnings only.

**Comment by SnailRabbids** [comment]
@DrMoriarty important!
I've noticed another problem, closing app cause a malloc error. (double click Home button -> application closes -> error)
Weird is, that clossing hiden application dont case an error. (click "Home" button -> application hides -> double click home button -> swipe application -> application closes)

**Comment by ayhanasker** [comment]
I have the same problem in my game. Did you find a solution?

einitialize FirebaseAnalytics
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib
malloc: *** error for object 0x283de2490: pointer being freed was not
malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by SnailRabbids** [comment]
@ayhanasker No, I didnt. But I've found another plugin and it works fine: https://github.com/funseek/godot-ios-firebase-analytics

**Comment by ayhanasker** [comment]
thank you. But I guess this module is not suitable for stable versions. I am using godot 3.4.2.stable version.

**Comment by SnailRabbids** [comment]
@ayhanasker I'm using the last version and it works for me :)
