### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by anisc** [DrMoriarty/godot-firebase-analytics#4]
Hi, 
Could you please explain how to use this plugin ? where to put the google-service.json 
This plugin : 
https://github.com/yalcin-ata/godot-android-plugin-firebase
require a change to be made on this file: godot-firebase-config.json, is there something similar to this ?
Thank you.

**Comment by DrMoriarty** [comment]
Hello!
You should put `google-services.json` into `android/build` folder.
The `google-services.json` you could download from your firebase console where you manage platforms of your project.

**Comment by DrMoriarty** [comment]
I updated READMI file with description of all available methods.

**Comment by anisc** [comment]
Man you are amazing thank you so much !!!
