### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by avnerh1** [DrMoriarty/godot-firebase-analytics#5]
I'm following the [guide](https://github.com/DrMoriarty/godot-firebase-analytics/blob/master/README.md), but when I use logEvent() in my dg script, the function is not recognized (which makes sense because according to the guide, all the changes were made solely in the "android" subfolder).
What am I doing wrong?

**Comment by DrMoriarty** [comment]
Show me the error message.

**Comment by avnerh1** [comment]
![image](https://user-images.githubusercontent.com/30798249/120845199-25c03400-c579-11eb-9a2f-921895116330.png)
I assume I need to add or AutoLoad some script to make it work, but the documentation doesn't say anything about that.

**Comment by DrMoriarty** [comment]
Gd wrapper for the plugin automatically added to your autoloading list. So you should call `fba.logEvent()` not just `logEvent`.
I will add this to README

**Comment by avnerh1** [comment]
Thank you.
