### ISSUE TITLE
No analytic logs found

### ISSUE THREAD

**Issue by kyoz** [DrMoriarty/godot-firebase-analytics#7]
Hi there, thank you so much for creating this cool addon. I'v successfully install this plugin but when running i doesn't see any log entries on Analytics Dashboard.

I'v autoload FBA, place `google-services.json` in `android/build` folder. I'v also call  `Fba.Screen(..)` on some screen.

When running in debug, i'v see `FirebaseAnalytics plugin inited!`

But when checking Analytic Dashboard (even in debug view). These's nothing.

I'v change firebase-analytics to 19.0.0 to build because it's conflict with other plugins i'm using. Don't know if this cause Analytics not work:

FirebaseAnalytics.gdap
```
remote=["com.google.firebase:firebase-analytics:19.0.0"]
```

Thank you very much

**Comment by DrMoriarty** [comment]
Could you show me logcat output of your game when you calling Fba functions?

**Comment by kyoz** [comment]
Hi @DrMoriarty , tracing with the logcat i'v see something like this:

```
06-30 13:12:21.129 16388 19014 V FA      : Deferring to Google Analytics for Firebase for event data collection. https://goo.gl/J1sWQy
06-30 13:12:21.153 16388 16388 I GodotPluginRegistry: Initializing Godot plugin FirebaseAnalytics
06-30 13:12:21.153 16388 16388 I GodotPluginRegistry: Completed initialization for Godot plugin FirebaseAnalytics
06-30 13:12:21.346 16388 19042 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
06-30 13:12:22.050 16388 19041 I godot   : FirebaseAnalytics plugin inited!
06-30 13:12:24.066 16388 19042 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
06-30 13:12:26.083 16388 19042 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
06-30 13:12:30.357 16388 19042 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
06-30 13:12:31.390 16388 19042 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
06-30 13:13:01.200 16388 19042 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
06-30 13:13:02.487 16388 19042 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
06-30 13:13:36.525 16388 19461 E FA      : Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
```

**Comment by kyoz** [comment]
I'v use `firebase-analytics_0.2.1_android.tgz` and add Fba autoload script to my project manually

**Comment by kyoz** [comment]
For more information, this is the remotes in all addons i'v use:

```
Admob
remote=["com.google.android.gms:play-services-ads:20.2.0", "com.google.android.ump:user-messaging-platform:1.0.0"]

Firebase Analytics
remote=["com.google.firebase:firebase-analytics:19.0.0"]

Google Play Billing
remote=["com.android.billingclient:billing:3.0.0"]

```

**Comment by DrMoriarty** [comment]
As far as I can see, the FBA told you what you should do: `Firebase Analytics disabled. See https://goo.gl/NAOOOI`

**Comment by kyoz** [comment]
Yah, i follow the instructor and config `build.gradle` manually and it work. Thank you very much :joy_cat:
